-- Run from the repository root: lua tests/test_language.lua
package.path = './tests/?.lua;' .. package.path
local mock = require('mock_mp')

local SCRIPT = 'portable_config/scripts/hikari-language.lua'
local SCRIPT_NAME = 'hikari_language'
local UOSC_CONF = 'portable_config/script-opts/uosc.conf'
local CODES = {'en', 'es', 'de', 'fr', 'it', 'pl', 'pt', 'ro', 'ru', 'tr', 'uk', 'zh-HK', 'zh-hans'}

local passed, failed = 0, 0
local function test(name, fn)
	local ok, err = pcall(fn)
	if ok then
		passed = passed + 1
		print('ok   ' .. name)
	else
		failed = failed + 1
		print('FAIL ' .. name .. '\n     ' .. tostring(err))
	end
end

local function eq(actual, expected, what)
	if actual ~= expected then
		error((what or 'value') .. ': expected ' .. tostring(expected) .. ', got ' .. tostring(actual), 2)
	end
end

local function read(path)
	local f = assert(io.open(path, 'rb'))
	local s = f:read('*a')
	f:close()
	return s
end

local function write(path, text)
	local f = assert(io.open(path, 'wb'))
	f:write(text)
	f:close()
end

-- Loads the script with `opts` as script-opts and `uosc_conf` (a path, or
-- false for none) as script-opts/uosc.conf; the shipped one by default.
local function load(opts, uosc_conf)
	mock.install(SCRIPT_NAME)
	mock.script_opts = opts or {}
	if uosc_conf ~= false then mock.config_files['script-opts/uosc.conf'] = uosc_conf or UOSC_CONF end
	HIKARI_LANGUAGE_TEST = true
	local chunk = assert(loadfile(SCRIPT))
	return chunk()
end

-- The change-list commands sent for `key` (script-opts append key=...), as values.
local function appended(key)
	local list = {}
	for _, cmd in ipairs(mock.commands) do
		if cmd[1] == 'change-list' and cmd[2] == 'script-opts' and cmd[3] == 'append' then
			local k, v = cmd[4]:match('^([^=]+)=(.*)$')
			if k == key then list[#list + 1] = v end
		end
	end
	return list
end

local function sent(message)
	local list = {}
	for _, cmd in ipairs(mock.commands) do
		if cmd[1] == 'script-message-to' and cmd[2] == 'uosc' and cmd[3] == message then list[#list + 1] = cmd[4] end
	end
	return list
end

-- The controls of the shipped uosc.conf, as uosc reads them.
local function shipped_controls()
	local value
	for line in read(UOSC_CONF):gmatch('[^\n]+') do
		if line:sub(1, 1) ~= '#' and line:match('^controls=') then value = line:sub(10) end
	end
	return value
end

test('uosc languages: the code then English; zh-HK by path too', function()
	local l = load()
	eq(l.uosc_languages('en'), 'en')
	eq(l.uosc_languages('es'), 'es,en')
	eq(l.uosc_languages('zh-hans'), 'zh-hans,en')
	eq(l.uosc_languages('zh-HK'), '~~/scripts/uosc/intl/zh-HK.json,zh-HK,en')
	eq(l.uosc_language_of('es,en'), 'es')
	eq(l.uosc_language_of('~~/scripts/uosc/intl/zh-HK.json,zh-HK,en'), 'zh-HK')
	eq(l.uosc_language_of('slang,en'), nil, 'uosc default: not one of ours')
	eq(l.uosc_language_of(nil), nil)
end)

test('saved file: both options, for every language; nothing for unknown codes', function()
	local l = load()
	eq(l.persist_content('es'), '# Generated by hikari-language.lua. Language: es\n'
		.. 'script-opts-append=hikari-language=es\nscript-opts-append=uosc-languages=es,en\n')
	for _, code in ipairs(CODES) do
		local text = l.persist_content(code)
		assert(text and text:find('hikari-language=' .. code .. '\n', 1, true), code)
		eq(select(2, text:gsub('\n', '')), 3, code .. ': three lines')
	end
	for _, bad in ipairs({'xx', 'es\nscript-opts-append=uosc-x=1', 'ES', '', 'auto'}) do eq(l.persist_content(bad), nil, bad) end
end)

test('the shipped hikari-language.conf picks no language (the system one, until a choice)', function()
	local text = read('portable_config/hikari-language.conf')
	for line in text:gmatch('[^\n]+') do assert(line:sub(1, 1) == '#', 'only comments: ' .. line) end
end)

test('menu: the 13 languages by their own name, the current one marked, in its language', function()
	local l = load({['hikari-language'] = 'es'})
	local data = l.menu_data()
	eq(data.type, 'hikari-language'); eq(data.title, 'Idioma'); eq(data.keep_open, true)
	eq(#data.items, 13, 'items')
	eq(data.items[1].title, 'English'); eq(data.items[2].title, 'Español'); eq(data.items[13].title, '简体中文')
	for i, item in ipairs(data.items) do
		eq(item.active, CODES[i] == 'es', CODES[i] .. ' active')
		eq(item.value[4], CODES[i], 'value')
		eq(item.value[1], 'script-message-to'); eq(item.value[2], SCRIPT_NAME); eq(item.value[3], 'select-language')
	end
	eq(data.items[2].hint, 'actual')
	l.open_menu()
	eq(#sent('open-menu'), 1, 'open-menu sent')
	assert(mock.bindings['open-menu'], 'binding')
end)

test('tooltips: the shipped controls get hikari tooltips in the language, the rest stays', function()
	local l = load({['hikari-language'] = 'en'})
	local controls = shipped_controls()
	eq(l.localize_controls(controls, 'en'), controls, 'English: the shipped text')
	local es = l.localize_controls(controls, 'es')
	for _, text in ipairs({'hikari_subs/open-menu?Subtítulos', 'hikari_upscale/open-menu?Escalado',
		'hikari_speed/open-menu?Velocidad', 'hikari_palettes/open-menu?Paletas',
		'hikari_update/open-menu?Actualizar hikari'}) do
		assert(es:find(text, 1, true), text)
	end
	eq(es:gsub('%?[^,]*', ''), controls:gsub('%?[^,]*', ''), 'only tooltips change')
	eq(l.localize_controls(es, 'es'), es, 'idempotent')
	eq(l.localize_controls(es, 'en'), controls, 'and back')
	local zh = l.localize_controls(controls, 'zh-hans')
	assert(zh:find('hikari_speed/open-menu?播放速度', 1, true), 'UTF-8 tooltips')
	eq(l.localize_controls(zh, 'en'), controls, 'back from Chinese')
end)

test('tooltips: conditions, badges, spaces, other buttons and a trailing comma', function()
	local l = load()
	local cases = {
		{'<has_many_audio,video>command:speed:script-binding hikari_speed/open-menu?Old',
			'<has_many_audio,video>command:speed:script-binding hikari_speed/open-menu?Velocidad'},
		{'command:speed:script-binding hikari_speed/open-menu', 'command:speed:script-binding hikari_speed/open-menu?Velocidad'},
		{'command : speed : script-binding hikari_speed/open-menu ? Old ? more',
			'command : speed : script-binding hikari_speed/open-menu?Velocidad'},
		{'command:palette:script-binding hikari_palettes/open-menu#sub>0?x', 'command:palette:script-binding hikari_palettes/open-menu#sub>0?Paletas'},
		{'command:star:script-binding other/open-menu?Mine', 'command:star:script-binding other/open-menu?Mine'},
		{'command:star:script-binding hikari_speed/open-menu-not?Mine', 'command:star:script-binding hikari_speed/open-menu-not?Mine'},
		{'cycle:repeat:loop-file:no/inf!?Bucle,menu,', 'cycle:repeat:loop-file:no/inf!?Bucle,menu,'},
		{'menu,gap,<video>command:speed:script-binding hikari_speed/open-menu?Speed,fullscreen,',
			'menu,gap,<video>command:speed:script-binding hikari_speed/open-menu?Velocidad,fullscreen,'},
		{'', ''},
	}
	for _, case in ipairs(cases) do eq(l.localize_controls(case[1], 'es'), case[2], case[1]) end
	-- A tooltip text with separators in it loses them.
	l.i18n.STRINGS.tooltip_speed.es = 'Velo, cidad?'
	eq(l.localize_config('command:speed:script-binding hikari_speed/open-menu', 'es'),
		'command:speed:script-binding hikari_speed/open-menu?Velo cidad')
end)

test('controls in effect: script-opts first, then uosc.conf read as mp.options reads it', function()
	local conf = os.tmpname()
	write(conf, '# controls=commented\r\ncontrols=first\r\n controls=not-a-key\ncontrols=last\r\nother=x\n')
	local l = load({}, conf)
	eq(l.conf_controls(), 'last', 'last one wins, CRLF and comments')
	eq(l.current_controls(), 'last')
	mock.script_opts['uosc-controls'] = 'from-opts'
	eq(l.current_controls(), 'from-opts', 'script-opts first')
	l = load({}, false)
	eq(l.current_controls(), nil, 'no uosc.conf: uosc default, nothing of hikari')
	write(conf, 'controls=' .. string.rep('x', 9000) .. '\n')
	l = load({}, conf)
	eq(l.current_controls(), nil, 'absurdly long: left alone')
	os.remove(conf)
end)

test('start-up: tooltips set only when they change', function()
	load({['hikari-language'] = 'en'})
	eq(#appended('uosc-controls'), 0, 'English with the shipped uosc.conf: nothing to do')
	load({['hikari-language'] = 'es'})
	local list = appended('uosc-controls')
	eq(#list, 1, 'Spanish: set once')
	assert(list[1]:find('?Paletas', 1, true), 'translated')
	load({['hikari-language'] = 'es'}, false)
	eq(#appended('uosc-controls'), 0, 'no uosc.conf')
end)

test('picking a language: option, file, OSD in the new language; everything follows', function()
	local path = os.tmpname()
	local l = load({['hikari-language'] = 'es', ['uosc-languages'] = 'es,en'})
	mock.expand['~~/hikari-language.conf'] = path
	mock.props['user-data/uosc/menu/type'] = 'hikari-language'
	mock.commands = {}
	l.select_language('fr')
	eq(appended('hikari-language')[1], 'fr', 'option set at once')
	eq(read(path), l.persist_content('fr'), 'saved')
	eq(mock.osd[#mock.osd], 'Redémarrez mpv pour traduire aussi les menus d’uosc', 'restart notice, in French')
	-- mpv then notifies every script of the option.
	mock.set_script_opt('hikari-language', 'fr')
	assert(appended('uosc-controls')[1]:find('?Palettes', 1, true), 'tooltips in French')
	local updates = sent('update-menu')
	eq(#updates, 1, 'open language menu redrawn')
	assert(updates[1]:find('"title":"Langue"', 1, true), 'in French')
	os.remove(path)
	mock.expand['~~/hikari-language.conf'] = nil
end)

test('picking the language uosc started with: no restart notice; same language: saved anyway', function()
	local path = os.tmpname()
	local l = load({['hikari-language'] = 'es', ['uosc-languages'] = 'es,en'})
	mock.expand['~~/hikari-language.conf'] = path
	mock.commands = {}
	l.select_language('es')
	eq(#appended('hikari-language'), 0, 'already the language')
	eq(read(path), l.persist_content('es'), 'saved')
	eq(#mock.osd, 0, 'no notice')
	l = load({}) -- no choice yet: uosc followed the subtitle language
	mock.expand['~~/hikari-language.conf'] = path
	l.select_language(l.i18n.language())
	eq(#mock.osd, 1, 'first choice: uosc may be in another language')
	os.remove(path)
	mock.expand['~~/hikari-language.conf'] = nil
end)

test('menu closed: a switch sends no update-menu', function()
	load({['hikari-language'] = 'es'})
	mock.commands = {}
	mock.set_script_opt('hikari-language', 'de')
	eq(#sent('update-menu'), 0)
end)

test('unknown codes are ignored; a save that fails says so', function()
	local l = load({['hikari-language'] = 'es'})
	mock.commands = {}
	for _, bad in ipairs({'xx', 'es,en', 'es\n', '../x', ''}) do l.select_language(bad) end
	eq(#mock.commands, 0, 'nothing done')
	eq(#mock.osd, 0)
	mock.logs.warn = {}
	l.select_language('es\nhikari: fake line ' .. string.rep('x', 200))
	local line = mock.logs.warn[1]
	assert(not line:find('%c'), 'no control characters in the log')
	assert(#line <= #'Ignoring unknown language: ' + 64, 'cut to 64 characters')
	mock.expand['~~/hikari-language.conf'] = '/nonexistent-dir/hikari-language.conf'
	l.select_language('de')
	eq(mock.osd[#mock.osd], 'hikari: Sprache konnte nicht gespeichert werden', 'in the language picked')
	mock.expand['~~/hikari-language.conf'] = nil
end)

test('the script avoids os.execute, io.popen and load*', function()
	local src = read(SCRIPT)
	for _, bad in ipairs({'os.execute', 'io.popen', 'loadstring', 'loadfile', 'dofile', 'load('}) do
		assert(not src:find(bad, 1, true), bad)
	end
end)

print(string.format('\n%d passed, %d failed', passed, failed))
os.exit(failed == 0 and 0 or 1)
